baseURL = "https://ksvblog.site/"
title = "K's V/Blog"
paginate = 7
theme = "harbor"
themesDir = "themes"
assetDir = "assets"

languageCode = "my"
languageName = "မြန်မာ"
DefaultContentLanguage = "my"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
disableKinds = ["404"]
enableEmoji = true

googleAnalytics = "UA-138756551-3"
disqusShortName = "heinhtetkyaw"
enableRobotsTXT = true
canonifyURLs = true
toc = true
more = true
# uglyurls = true

author = "Hein Htet Kyaw"

[markup.goldmark.renderer]
  unsafe= true

[params.logo]
  url = "icon.svg"
  width = 50
  height = 50
  alt = "Logo"

# [Author]
#   name = "Hein Htet Kyaw"

[params]
  favicon = "favicon.ico"
  sitename = "K's V/Blog"
  author = "Hein Htet Kyaw"
  description = "You can read Kiddo's Blogs again, Extra you can watch Video Tutorials later too."

  twitter = "@HeinHtetKyaw_"
  github = "https://github.com/h2kyaw"
  facebook = "https://facebook.com/heinhtetkyaw.blog"

  ogimage = "/images/og.jpg"
  images = ["/images/og.jpg"]

  mainSections = ["post"]
  readingTime = true
  toc = true
  more = true

  customCSS = ["/css/custom.css"] # in case you use `/static/css/custom.css`

  enableGoogleAnalytics = true
  gtm = "GTM-55RVH82"

[params.license]
    name = "CC BY-NC-ND 4.0"
    nameLong = "Attribution-NonCommercial-NoDerivatives 4.0 International"
    copyrightFirstYear = 2012

[permalinks]
	post = "/post/:year/:filename/"
	page = "/page/:filename/"

[outputs]
    section = ["JSON", "HTML", "RSS"]

[[params.nav]]
  identifier = "/about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/page/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tags fa-lg"
  url = "tags"
  weight = 3

[[params.nav]]
  identifier = "categories"
  name = "Category"
  icon = "fas fa-folder-open fa-lg"
  url = "categories"
  weight = 3

[[params.nav]]
  identifier = "ebooks"
  name = "eBooks"
  icon = "fas fa-book fa-lg"
  url = "/page/ebooks/"
  weight = 3

[[params.nav]]
  identifier = "archives"
  name = "Archives"
  icon = "fas fa-archive fa-lg"
  url = "/page/archives"
  weight = 3

# [[params.nav]]
#  identifier = "search"
#  name = "Search"
#  icon = "fas fa-search fa-lg"
#  url = "search"
#  weight = 3

[[params.social]]
  name= "Facebook"
  url="https://www.facebook.com/heinhtetkyaw.blog"
  icon="fab fa-facebook"

[[params.social]]
  name= "Twitter"
  url="https://www.twitter.com/HeinHtetKyaw_"
  icon="fab fa-twitter"

[[params.social]]
  name= "Twitter"
  url="https://www.youtube.com/channel/UCsxb9mQZlUeNuLZvF_ctyIA"
  icon="fab fa-youtube"

[[params.social]]
  name= "Twitter"
  url="https://www.linkedin.com/in/h2kyaw/"
  icon="fab fa-linkedin"

[[params.social]]
  name= "Keybase"
  url="https://www.keybase.com/heinhtetkyaw"
  icon="fab fa-keybase"

# [languages]
#   [languages.my]
#     languageName = "မြန်မာ"
#     languageCode = "my"
#     weight = 1
#   [languages.en]
#     languageName = "English"
#     languageCode = "en-us"
#     weight = 2

[frontmatter]
  date = ['date', 'publishdate', 'pubdate', 'published', 'lastmod', 'modified']
  expiryDate = ['expirydate', 'unpublishdate']
  lastmod = [':git', 'lastmod', 'modified', 'date', 'publishdate', 'pubdate', 'published']
  publishDate = ['publishdate', 'pubdate', 'published', 'date']

