baseURL = "https://h2kyaw.github.io/"
title = "K's V/Blog"
paginate = 5

languageCode = "my"
languageName = "Myanmar"

DefaultContentLanguage = "my"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
theme = "harbor"
disableKinds = ["404"]

googleAnalytics = "UA-138756551-3"
disqusShortName = "heinhtetkyaw"
enableRobotsTXT = true
canonifyURLs = true

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"
  readingTime = true

  author = "Hein Htet Kyaw"
  description = "You can read Kiddo's Blogs again, Extra you can watch Video Tutorials later too."

  github = "https://github.com/h2kyaw"
  facebook = "https://facebook.com/heinhtetkyaw.blog"
  
  ogimage = "/images/og.jpg"
  images = ["/images/og.jpg"]
  
  sitename = "K's V/Blog"
  twitter = "@HeinHtetKyaw_"

  enableGoogleAnalytics = true

[permalinks]
	post = "/:year/:filename/"
	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML", "RSS"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "ebooks"
  name = "eBooks"
  icon = "fas fa-book fa-lg"
  url = "/ebooks/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "tags"
  weight = 3

[[params.nav]]
  identifier = "categories"
  name = "Category"
  icon = "fas fa-folder-open fa-lg"
  url = "categories"
  weight = 3

[[params.nav]]
  identifier = "archives"
  name = "Archives"
  icon = "fas fa-archive fa-lg"
  url = "archives"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "search"
  weight = 3

[[params.social]]
  name= "Facebook"
  url="https://www.facebook.com/heinhtetkyaw.blog"
  icon="fab fa-facebook"

[[params.social]]
  name= "Twitter"
  url="https://www.twitter.com/HeinHtetKyaw_"
  icon="fab fa-twitter"

[[params.social]]
  name= "Twitter"
  url="https://www.youtube.com/channel/UCsxb9mQZlUeNuLZvF_ctyIA"
  icon="fab fa-youtube"

[[params.social]]
  name= "Twitter"
  url="https://www.linkedin.com/in/h2kyaw/"
  icon="fab fa-linkedin"

[params.logo]
  url = "icon.svg"
  width = 50
  height = 50
  alt = "Logo"

[languages]
  [languages.my]
  languageName = "Myanmar"
  languageCode = "my"
  weight = 1